#!/usr/bin/env bash
# calc number of argument passed
# Disable strict host key checking for SCP
SCP_OPTIONS="-o StrictHostKeyChecking=no"

len=$#

if [ $len -lt 3 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
# elif [ $len -lt 4 ]; then
#     scp -i $4 $1 $3@$2:~/
else
    scp $SCP_OPTIONS -i $4 $1 $3@$2:~/
fi