#!/usr/bin/env bash
# listen to port 80
conf="server {
        listen 80 default_server;
        listen [::]:80 default_server ipv6only=on;

        root /usr/share/nginx/html;
        index index.html index.htm;

        server_name localhost;

        location /{
            try_files $uri $uri/ =404;
        }

}"

echo "$conf" | sudo tee /etc/nginx/conf.d/hbnb.conf
sudo service nginx restart
