#!/usr/bin/env bash
# information about the school file.
if [ $'(file school 2> /tmp/null)' ]; then
	echo "school file exists"
	str=$(file school | cut -d ':' -f 2)
	if [ "$str" = " empty" ]; then
		echo "school file is empty"
	else
		echo "school file is not empty"
	fi
	echo "school is a regular file"
else
	echo "school file does not exist"
fi
